static_sites:
  - type: static_site
    name: movie-ticket-frontend
    plan: free
    buildCommand: chmod -R 755 node_modules/.bin && npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://movie-ticket-backend.onrender.com
      - key: REACT_APP_NODE_ENV
        value: production